// Localhost
###
# Get all individuals information
GET http://localhost:3000/individuals
###
# Gets specific Individual information (katelyndblunck)
GET http://localhost:3000/individuals/6406cc81963388d643478996
### Creates new Individual (SenorMustach)
POST http://localhost:3000/individuals
Content-type: application/json

{
    "firstName":"Hoyt","lastName":"Goodwill","username":"SenorMustach", "level":"1", "gameNumber":"6", "friends":"11"
}

